# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5a7e67c9efe3b9553aaad531e650d32a86aa09e15adae40a2d5439617b2465030067697c4478cda8b9cac4c6c5612bddf480989d3caf1b3e84ebf3285c35624

test:
  secret_key_base: 8ab5f6d1f4849de9c780ccd7eebfe43099b2b6111fbd92d5c89f10aeb7cc7843c72e6ed7ee8d27eeeab79bebf783434f78a4d81792bc2838a7d17bf8399cbd63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
